# Generated by Django 6.0.6 on 2026-07-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_type',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
